[package]
name = "shiki-langs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
description = "Bundled TextMate language grammars for shiki"
readme = "README.md"
include = ["Cargo.toml", "README.md", "src/**", "assets/**", "examples/**", "tests/**"]

[dependencies]
shiki-core = { workspace = true, features = ["json"] }

[dev-dependencies]
shiki-themes.workspace = true
