[package]
name = "shiki-langs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Bundled TextMate language grammars for shiki"
include = ["Cargo.toml", "src/**", "assets/**", "examples/**", "tests/**"]

[dependencies]
shiki.workspace = true

[dev-dependencies]
shiki-themes.workspace = true
