[package]
name = "shiki"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
description = "Feature-gated facade for fast TextMate highlighting in Rust"
readme = "README.md"

[features]
default = ["json"]
json = ["shiki-core/json"]
langs = ["dep:shiki-langs"]
themes = ["dep:shiki-themes"]
macros = ["dep:shiki-macros"]
full = ["json", "langs", "themes", "macros"]

[dependencies]
shiki-core.workspace = true
shiki-langs = { workspace = true, optional = true }
shiki-macros = { workspace = true, optional = true }
shiki-themes = { workspace = true, optional = true }
