[package]
name = "shiki-themes"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
description = "Bundled TextMate themes for shiki"
readme = "README.md"
include = ["Cargo.toml", "README.md", "src/**", "assets/**"]

[dependencies]
shiki-core = { workspace = true, features = ["json"] }
